name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: '5.1'

    - name: Install LuaUnit
      run: luarocks install luaunit

    - name: Run tests
      run: lua test_all.lua